### PR TITLE
[20] - Created an Example Form that can be filled with voice commands using digit components 

### PR DESCRIPTION
**Pull request by EuclidStellar**
## Description
#20 
This PR adds a voice-command feature to fill a form in the app. The form consists of three fields: Name, Phone Number, and Email. Users can fill these fields by speaking into the microphone. The app uses the `speech_to_text` package to convert speech to text and the `flutter_tts` package to convert text to speech. Additionally, the app utilizes the `DigitTextField` widget from the `digit_components` package to create the form fields.

### Features Added:
1. **Voice Command to Fill Form Fields:**
   - The app listens for voice commands when a field is focused and updates the corresponding field with the recognized text.
   - The app speaks the label of the focused field to guide the user on what to say.
   
2. **Form Validation:**
   - The app uses the `Form` widget to validate the form fields.
   - A snackbar is displayed when the form is successfully submitted.

3. **User Interaction:**
   - The app uses the `IconButton` widget to start and stop listening for voice commands.
   - The `FocusNode` widget is used to track which field is currently focused.
   - The `ScaffoldMessenger` widget is used to show a snackbar when the form is successfully submitted.
   - The `FlutterTts` widget is used to speak the label of the focused field.

### Packages Used:
- [Fluttertts](https://pub.dev/packages/flutter_tts)
- [Speech to text](https://pub.dev/packages/speech_to_text)
- [Digit components](https://pub.dev/packages/digit_components)

### Initialization:
- Initialized `speech_to_text` and `flutter_tts` objects in the `initState` method.
- Created focus nodes for each field to track the current focus.

### Voice Commands:
- `_speakLabelText`: Speaks the label of the focused field to guide the user.
- `_listen`: Listens for voice commands and updates the form fields with the recognized text.

### Form Validation:
- `_submitForm`: Validates the form fields and displays a snackbar on successful submission.

### UI Components:
- Used `DigitTextField` for the form fields.
- Used `IconButton` to start and stop listening for voice commands.
- Used `Focus` to track the focus state of the form fields.

## Checklist
- [x] Added voice command functionality to fill form fields.
- [x] Implemented form validation and snackbar notifications.
- [x] Integrated `speech_to_text` and `flutter_tts` packages.
- [x] Used `DigitTextField` from `digit_components` package.
- [x] Created UI components to handle voice commands and form submission.

## Testing
- Tested the voice command functionality for filling the form fields.
- Verified form validation and snackbar notifications.
- Ensured compatibility with the `speech_to_text`, `flutter_tts`, and `digit_components` packages.

## References
- [Fluttertts](https://pub.dev/packages/flutter_tts)
- [Speech to text](https://pub.dev/packages/speech_to_text)
- [Digit components](https://pub.dev/packages/digit_components)

## Additional Notes
*Documented the code for better readability*

### CODE REVIEW

**Comment by Ramkrishna-egov** [comment]
@EuclidStellar Lets keep this PR open, And you keep pushing further changes to your branch.

**Review by Ramkrishna-egov — APPROVED** [review]
Approved, and yet to be merged

**Comment by EuclidStellar** [comment]
Used Reactive Text Form field in code along with form control in last commit 

DigitTextField ----> DigitTextFormField

**Comment by EuclidStellar** [comment]
Added more Digit Component enabled with voice commands such as DigitReactiveDropDown
First tried to implement it on the Flutter Material 3 widget and then transitioned it to DigitReactiveDropDown

**Comment by EuclidStellar** [comment]
added voice command in Digit Component ( DigitCheckBoxTile ) ( reactive checkbox )
used agreed as a keyword to mark tick in checkbox

**Comment by EuclidStellar** [comment]
> added voice command in Digit Component ( DigitCheckBoxTile ) ( reactive checkbox ) used agreed as a keyword to mark tick in checkbox

corrected the header documentation

**Comment by EuclidStellar** [comment]
added DigitTextFormField integrated with voice enabling command

**Comment by EuclidStellar** [comment]
Without Internet Bug Resolved Ready for Presentation

**Pull request closed without merging**
